### ISSUE TITLE
Format Cross-sells to match design file

### ISSUE THREAD

**Issue by chazzels** [chazzels/Spectrum#24]
upsells is activated in the appropriate place and will hide if the product does not have any upsells associated with it. The design will not exactly match the design file due to how woocommerce functions.

**Comment by ericspectrum** [comment]
what are the expected differences?  can we at least have the inline format rather than the slider?  maybe we need a plugin?

**Comment by zoeligon** [comment]
upsells is currently on product page as "spectrum recommends" and this needs to be cross sells instead

**Comment by chazzels** [comment]
ERIC: expected differences are no radio style buttons. inline can be done.

ZOE: On the development site, the cross sells have been reformatted to say "spectrum boutique recommends:" as the design shows.

**Comment by salbono** [comment]
This is one of the area that I mentioned may give us some trouble in the initial phone call. We got everything up and working so it is in place and completely functional. We have some constraints in formatting due to woo commerce frameworks. There is not an option for a radio click add to cart. There are plug-ins available with similar features, but the products would all have to be reworked. Given the potential workload that would be for Eric, Zoe and the team I think the design will require further discussion.
