### ISSUE TITLE
product page mobile formatting issues

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#27]
(title,brand, price) needs to be above image.

shipping info link is missing

Spectrum recommends product slider-   should be after cart/wishlist/shipping info and before description/specs/reviews

ADD TO (wishlist)  - txt missing - if not there intentionally please explain. also there are better wishlist plugin's i'm pretty sure, ones that have smart reminders to purchase your wishlist items, etc.  Also we need a view wishlist link next to view cart.

Description/Specs/Reviews - any way to make this a menu like the mobile mockup?

**Comment by chazzels** [comment]
-Shipping Info: it looks like some old styles caused a problem.

-Spectrum recommends: This is currently an issue that has to do with the how the page is made responsive. Because it shows up structurally after the price it is going to show up in the same spot on mobile as well. investigating solutions.

-ADD TO (wishlist): this is really odd. I am looking into why this may have changed. I am guessing just a control panel change in the backend.

-DESCRIPTION/SPECS/REVIEWS: unfortunately no. the tabbed structure you see currently is already a rebuilt version of the vanilla woocommerce. We would have to quite a bit code that could make the site run poorly on product pages. looking at other approaches.

**Comment by ericspectrum** [comment]
did you see the email about using a product slider to solve the spectrum recommends formatting issues?

**Comment by ericspectrum** [comment]
http://codecanyon.net/item/woocommerce-related-products-slider/5395073

**Comment by ericspectrum** [comment]
![Uploading image.png…]()

**Comment by ericspectrum** [comment]
Product titles and price need to be above image

**Comment by ericspectrum** [comment]
![image](https://cloud.githubusercontent.com/assets/16167470/13091666/e30199b8-d4c1-11e5-80cc-ceb3371d4a6e.png)

**Comment by salbono** [comment]
Added after "add to cart button" on mobile
